quizzes/urls.py
from django.urls import include, path
from . import views

app_name = "quizzes"
urlpatterns = [
    path("", views.home_view, name="home"),
    path("create-quiz/", views.create_quiz, name="create-quiz"),
    path("quiz/<int:id>", views.quiz_view, name="quiz-view"),
    path("quiz/<int:quiz_id>/question/<int:question_id>", views.quiz_question_view, name="quiz-question-view"),
    path("quiz/<int:quiz_id>/results", views.quiz_results, name="quiz-results-view"),
    path("categories/", views.categories_view, name="categories"),
    path("categories/<slug:slug>/", views.category_detail_view, name="category-detail-view"),
    path("question/<slug:slug>/", views.question_detail_view, name="question-detail-view"),
    path("question/try-again/<int:question_id>", views.try_again_view, name="try-again-view"),
]

quizzle2/urls.py
from django.conf import settings
from django.conf.urls import url

from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic import TemplateView

from django.contrib import admin


urlpatterns = [
    path("", include("quizzes.urls", namespace="quizzes")),
    path("", TemplateView.as_view(template_name="homepage.html"), name="home"),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

quizzes/models.py
from django.db import models
from django.utils.text import slugify
import itertools
from django.contrib.auth.models import User


class Category(models.Model):
    """Categories that questions can be in"""
    name = models.CharField(max_length=200, unique=True)
    published = models.BooleanField(default=False)
    description = models.TextField(default="Description for Category")
    slug = models.SlugField(max_length=200, unique=True, null=True, blank=True)


    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def active_questions(self):
        return self.questions.filter(published=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            max_length = 200
            self.slug = orig = slugify(self.name)[:max_length]

            for x in itertools.count(1):
                if not Question.objects.filter(slug=self.slug).exists():
                    break

                # Truncate the original slug dynamically. Minus 1 for the hyphen.
                self.slug = "%s-%d" % (orig[:max_length - len(str(x)) - 1], x)

        return super(Category, self).save(*args, **kwargs)


class Question(models.Model):

    question_text = models.CharField(max_length=200)
    title = models.CharField(max_length=120, null=True, blank=True)
    slug = models.SlugField(max_length=200, unique=True, null=True)
    category = models.ForeignKey(Category, related_name='questions', on_delete=models.CASCADE)
    published = models.BooleanField(default=False)
    save_for_exam = models.BooleanField(default=False)
    # Access all choices through related_name "choices"

    def save(self, *args, **kwargs):
        if not self.slug:
            max_length = 200
            self.slug = orig = slugify(self.question_text)[:max_length]

            for x in itertools.count(1):
                if not Question.objects.filter(slug=self.slug).exists():
                    break

                # Truncate the original slug dynamically. Minus 1 for the hyphen.
                self.slug = "%s-%d" % (orig[:max_length - len(str(x)) - 1], x)

        return super(Question, self).save(*args, **kwargs)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, related_name="choices", on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    description = models.CharField(max_length=200, blank=True, null=True)
    is_correct = models.BooleanField()
    order = models.PositiveSmallIntegerField(null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.choice_text



class Quiz(models.Model):

    student = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz_num_for_student = models.IntegerField()
    question_ids = models.TextField()
    num_questions = models.IntegerField()
    complete = models.BooleanField(default=False)
    final_score = models.DecimalField(blank=True, null=True, decimal_places=2, max_digits=5)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Quizzes'

    def __str__(self):
        return "Quiz {}".format(self.quiz_num_for_student)




class QuestionResponse(models.Model):

    student = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="responses", null=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice,  on_delete=models.CASCADE)
    attempt_number = models.PositiveSmallIntegerField(blank=True, null=True)

    # Note attempt number is the number of attempts on this quiz or in free form


class QuestionStatus(models.Model):

    student = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, null=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    feedback_view = models.BooleanField(default=False)
    has_attempted = models.BooleanField(default=False)


    class Meta:
        unique_together = (("student", "question", "quiz"),)

quizzes/views.py
from django.shortcuts import render, redirect, reverse
from .models import Category, Question, Quiz, QuestionResponse, QuestionStatus, Choice
from django.shortcuts import get_object_or_404
import random
import json

def home_view(request):

    user = request.user

    if not user.is_authenticated:
        return render(request, "homepage.html")

    context = {
        "welcome_message": "Hello, and welcome {}!".format(user),
        "categories": [{"name": cat.name, "id": cat.id} for cat in Category.objects.filter(published=True)],
        "quizzes": Quiz.objects.filter(student=request.user),
    }

    return render(request, "quizzes/dashboard.html", context)



def create_quiz(request):

    if request.method == "POST":

        # This is ineffcient of course
        data = dict(request.POST)
        print(data)
        # print("Categories is {}".format(dict(data).get('categories')))
        questions = Question.objects.filter(category__pk__in=data['categories'])
        num_questions = int(data.get("num_questions")[0])
        print(list(questions))

        sample_size = num_questions if num_questions < len(questions) else len(questions)
        print(sample_size)

        question_on_quiz = [q.id for q in random.sample(list(questions), sample_size)]

        print("Quiz qs {}".format(question_on_quiz))

        quiz_num_for_student = Quiz.objects.filter(student=request.user).count() + 1

        quiz = Quiz.objects.create(student=request.user,
                               num_questions=num_questions,
                               question_ids=json.dumps(question_on_quiz),
                               quiz_num_for_student=quiz_num_for_student)

    return redirect("quizzes:quiz-view", id=quiz.id)

def quiz_question_view(request, quiz_id, question_id):

    quiz = get_object_or_404(Quiz, pk=quiz_id, student=request.user)
    question = get_object_or_404(Question, pk=question_id)

    question_ids = json.loads(quiz.question_ids)
    questions_dict = dict(zip(range(len(question_ids)), question_ids))
    prev_question_id = questions_dict.get(question_ids.index(question_id) - 1)
    next_question_id = questions_dict.get(question_ids.index(question_id) + 1)

    context = {"quiz": quiz,
               "prev_question_id": prev_question_id,
               "next_question_id": next_question_id,
               }

    print(quiz)

    try:
        question_response = QuestionResponse.objects.get(
            student=request.user,
            question=question,
            quiz=quiz,
        )


        context['question_response'] = question_response

        return render(request, "quizzes/question_feedback.html", context)

    except QuestionResponse.DoesNotExist:
        pass

    if request.method == "POST":
        answer_id = request.POST.get("answer-chosen")
        choice = Choice.objects.get(id=answer_id)
        question_response = QuestionResponse.objects.create(
                                student=request.user,
                                quiz=quiz,
                                question=question,
                                choice=choice
                            )
        context['question_response'] = question_response
        return render(request, "quizzes/question_feedback.html", context)

    # Request is GET and has not been seen before

    context['question'] = question
    return render(request, "quizzes/question_detail.html", context)

def quiz_view(request, id):

    quiz = get_object_or_404(Quiz, pk=id, student=request.user)
    questions = json.loads(quiz.question_ids)
    first_question_id = questions[0]

    return redirect("quizzes:quiz-question-view", quiz_id=id, question_id=first_question_id)


def quiz_results(request, quiz_id):

    quiz = get_object_or_404(Quiz, pk=quiz_id, student=request.user)
    quiz.complete = True
    quiz.save()

    total_score = (len(quiz.responses.all().filter(choice__is_correct=True))/len(quiz.responses.all())) * 100

    context = {"quiz": quiz,
               "total_score": total_score}
    return render(request, "quizzes/quiz_results.html", context)


def categories_view(request):

    categories = Category.objects.filter(published=True)
    context = {"categories": categories}

    return render(request, "quizzes/categories.html", context)


def category_detail_view(request, slug):

    category = get_object_or_404(Category, slug=slug)
    questions = category.active_questions()

    for q in questions:
        has_attempted = QuestionResponse.objects.filter(question=q, quiz=None).exists()
        q.has_attempted = has_attempted


    context = {"category": category, "personal_questions": questions}

    return render(request, "quizzes/category_detail.html", context)


def question_detail_view(request, slug):


    question = get_object_or_404(Question, slug=slug)
    question_status, _created = QuestionStatus.objects.get_or_create(question=question, student=request.user, quiz=None)

    context = {"question": question,
               "question_status": question_status}

    if request.method == "POST":
        answer_id = request.POST.get("answer-chosen")
        choice = Choice.objects.get(id=answer_id)
        question_response = QuestionResponse.objects.create(
            student=request.user,
            quiz=None,
            question=question,
            choice=choice
        )

        question_status.has_attempted = True
        question_status.save()
        context['question_response'] = question_response
        return render(request, "quizzes/question_feedback.html", context)

    if question_status.feedback_view:
        question_response = QuestionResponse.objects.filter(student=request.user, question=question, quiz=None).first()
        context['question_response'] = question_response
        print("Found question response {}".format(question_response))
        return render(request, "quizzes/question_feedback.html", context)

    print(context)
    return render(request, "quizzes/question_detail.html", context)


def try_again_view(request, question_id):


    question = Question.objects.get(pk=question_id)
    question_status = QuestionStatus.objects.get(student=request.user, question=question, quiz=None)
    question_status.feedback_view = False
    return redirect("quizzes:question-detail-view", slug=question.slug)

quizzle2/templates/quizzes/categories.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}Quizzle 2{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
<main>
    <section id="content-section">
        <div id="content-body">

            <div class="text-center">
                <h1>Categories</h1>
            </div>
            <hr>
            <div class="card-columns">
            {% for cat in categories %}

            <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{ cat }}</h5>
                <p class="card-text">{{ cat.description }}</p>
                  <!--<a href="#" class="btn btn-secondary"><i class="far fa-star"></i></a>&nbsp&nbsp-->
                  <a href="{% url "quizzes:category-detail-view" cat.slug %}" class="btn btn-primary">View Questions</a>
              </div>
                <div class="card-footer">
                  <small class="text-muted">{{ cat.active_questions.count }} Questions Available</small>
                </div>
            </div>
            {% endfor %}
            </div>

        </div>
    </section>

</main>


{% endblock %}

quizzle2/templates/quizzes/category_detail.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}Quizzle 2{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
<main>
    <section id="content-section">
        <div id="content-body">

            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{% url "quizzes:home" %}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{% url "quizzes:categories" %}">Categories</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ category }}</li>
              </ol>
            </nav>
            <br><br>
            <h3>{{ category }} Questions</h3>

            <table class="table">
              <thead>
                <tr>
                  <th style="width: 5%" scope="col">#</th>
                  <th style="width: 35%" scope="col">Name</th>
                  <th style="width: 10%" scope="col">Has attempted?</th>
                </tr>
              </thead>
              <tbody>
                {% for q in personal_questions %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                    <td><a href="{% url "quizzes:question-detail-view" q.slug %}">{{ q }}</a></td>
                  <td class="text-center" style="font-size: 200%;">
                      {% if q.has_attempted %}Yes{% else %}No{% endif %}
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
                {{ q }}

        </div>
    </section>

</main>


{% endblock %}

quizzle2/templates/quizzes/dashboard.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}Quizzle 2{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
<main>
    <section class="jumbotron">
        <div class="container">
            {% include "_messages.html" %}
            <h1>{{ welcome_message }}</h1>
        </div>
    </section>
    <section id="content-section">

        <div id="content-body">

            <br>
            <div class="row">
                <div class="col-md-4 offset-md-2">
                    <div class="text-center">
                        <a href="{% url "quizzes:categories" %}" class="btn btn-secondary btn-lg active float-right" role="button" aria-pressed="true">Check Out Categories</a>
                    </div>
                </div>
                <br><br>

            <div class="col-md-4">
                <div class="text-center">
                    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#create-quiz-modal">
                        Create New Quiz
                    </button>
                </div>
            </div>
            </div>
            {% if quizzes %}

            <br><br>
            <h3>Your Quizzes</h3>

            <table class="table">
              <thead>
                <tr>
                  <th style="width: 5%" scope="col">#</th>
                  <th style="width: 25%" scope="col">Quiz</th>
                  <th style="width: 15%" scope="col"># Questions</th>
                  <th style="width: 15%" scope="col">Created</th>
                  <th style="width: 15%" scope="col">Results</th>
                </tr>
              </thead>
              <tbody>
                {% for q in quizzes %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                    <td><a href="{% url "quizzes:quiz-view" q.id %}">{{ q }}</a></td>
                    <td>{{ q.num_questions }}</td>
                    <td>{{ q.created }}</td>
                    <td>{% if q.complete %}<a href="{% url "quizzes:quiz-view" q.id %}">Results</a>{% else %}<a href="{% url "quizzes:quiz-view" q.id %}">Continue{% endif%}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
                {{ q }}

            {% endif %}
        </div>
    </section>

</main>

<!-- Modal -->
<div class="modal fade" id="create-quiz-modal" tabindex="-1" role="dialog" aria-labelledby="create-quiz-modal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Create a Quiz</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <form action="{% url "quizzes:create-quiz" %}" method="POST">
            {% csrf_token %}
      <div class="modal-body">
            <p>What categories would you like to include?</p>
            {% for cat in categories %}
            <div class="form-check">
              <input class="form-check-input" type="checkbox" name="categories" value="{{ cat.id }}" id="{{ cat.id }}">
              <label class="form-check-label" for="{{ cat.id }}">
                {{ cat.name }}
              </label>
            </div>
            {% endfor %}

            <br>
            <div class="form-group">
                <label for="num_questions">How many questions should it have?</label>
                <select name="num_questions" class="form-control" id="num_questions">
                  <option>1</option>
                  <option>2</option>
                  <option>5</option>
                  <option>10</option>
                  <option>20</option>
                </select>
              </div>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input type="submit" class="btn btn-primary" value="Submit">


      </div>
            </form>
    </div>
  </div>
</div>

{% endblock %}

quizzle2/templates/quizzes/question_detail.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}Quizzle 2{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
<main>
    <section id="content-section">
        <div id="content-body">

            {% if quiz %}
                <p><a href="{% url "quizzes:home" %}">< Back to Quizzes</a></p>
                <h1>{{ quiz }}<span class="badge badge-secondary float-right">{{ question.category }}</span></h1>

            {% else %}

                <p><a href="{% url "quizzes:category-detail-view" question.category.slug %}">< Back to {{ question.category }} </a></p>

            {% endif %}

            <br><br>
            <h3 class="text-center">{{ question.question_text }}</h3>


            <form action="" method="post">
                {% csrf_token %}
                {% for choice in question.choices.all %}
                <br><br>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="answer-chosen" id="{{ choice.id }}" value="{{ choice.id }}">
                  <label class="form-check-label" for="{{ choice.id }}">
                    {{ choice.choice_text }}
                  </label>
                </div>
                {% endfor %}
                <br><br><br>
                {% if question_status.has_attempted %}
                <!--<input type="submit" class="btn btn-secondary btn-lg" value="View Previous Attempts">-->
                {% endif %}
                <input type="submit" class="btn btn-primary btn-lg" value="Submit">
                <br><br><br>
            </form>

        </div>
    </section>

</main>


{% endblock %}

quizzle2/templates/quizzes/question_detail_old.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}Quizzle 2{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
<main>
    <section id="content-section">
        <div id="content-body">

            <p><a href="{% url "quizzes:category-detail-view" question.category.slug %}">< Back to {{ question.category }} </a></p>

            <br><br>
            <h3 class="text-center">{{ question.question_text }}</h3>


            <form action="" method="post">
                {% csrf_token %}
                {% for choice in question.choices.all %}
                <br><br>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="answer-chosen" id="{{ choice.id }}" value="{{ choice.id }}">
                  <label class="form-check-label" for="{{ choice.id }}">
                    {{ choice.choice_text }}
                  </label>
                </div>
                {% endfor %}
                <br><br><br>
                <input type="submit" class="btn btn-primary btn-lg" value="Submit">
                <br><br><br>
            </form>

        </div>
    </section>

</main>


{% endblock %}

quizzle2/templates/quizzes/question_feedback.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}Quizzle 2{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
<main>
        <div id="content-body">
            {% if quiz %}<p><a href="{% url "quizzes:home" %}">< Back to Quizzes</a></p>{% endif %}
            {% if question_response.choice.is_correct %}
                <div class="alert alert-success" role="alert">
                  Correct! Good job!
                </div>

            {% else %}
                <div class="alert alert-danger" role="alert">
                  It looks like your answer is wrong!
                </div>

            {% endif %}

            {% if quiz %}
                <h1>{{ quiz }}<span class="badge badge-secondary float-right">{{ question_response.question.category }}</span></h1>

            {% else %}

                <p><a href="{% url "quizzes:category-detail-view" question.category.slug %}">< Back to {{ question.category }} </a></p>

            {% endif %}

            <br><br>
            <h3 class="text-center">{{ question_response.question.question_text }}</h3>

            <form>
                {% for choice in question_response.question.choices.all %}
                <br><br>
                <div class="form-check">
                  <input disabled class="form-check-input" type="radio" name="answer-chosen" id="{{ choice.id }}" value="{{ choice.id }}"
                         {% if choice.id == question_response.choice.id %}checked {% endif %}
                  >
                  <label class="form-check-label" for="{{ choice.id }}">
                    {{ choice.choice_text }}
                  </label>
                </div>
                {% endfor %}

            </form>
                <br><br><br>
                {% if quiz %}
                    {% if next_question_id %}
                        <a href="{% url "quizzes:quiz-question-view" quiz.id next_question_id %}" class="btn btn-secondary btn-lg active float-right" role="button" aria-pressed="true">Next Question -></a>
                    {% else %}
                        <a href="{% url "quizzes:quiz-results-view" quiz.id %}" class="btn btn-secondary btn-lg active float-right" role="button" aria-pressed="true">View Final Results</a>
                    {% endif %}

                {% else %}
                    <form action="{% url "quizzes:try-again-view" question_response.question.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-secondary btn-lg active " role="button" aria-pressed="true">Try Again</button>
                    </form>
                {% endif %}
                <br><br><br>


        </div>
    </section>

</main>


{% endblock %}

quizzle2/templates/quizzes/quiz.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}Quizzle 2{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
<main>
    <section id="content-section">
        <div id="content-body">

            <p><a href="{% url "quizzes:home" %}">< Back to Quizzes</a></p>
            <h1>{{ quiz }}<span class="badge badge-secondary float-right">{{ question.category }}</span></h1>

            <br><br>
            <h3 class="text-center">{{ question.question_text }}</h3>


            <form action="" method="post">
                {% csrf_token %}
                {% for choice in question.choices.all %}
                <br><br>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="answer-chosen" id="{{ choice.id }}" value="{{ choice.id }}">
                  <label class="form-check-label" for="{{ choice.id }}">
                    {{ choice.choice_text }}
                  </label>
                </div>
                {% endfor %}
                <br><br><br>
                <input type="submit" class="btn btn-primary btn-lg float-right" value="Submit">
                <br><br><br>
            </form>

        </div>
    </section>

</main>


{% endblock %}

quizzle2/templates/quizzes/quiz_feedback.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}Quizzle 2{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
<main>
        <div id="content-body">
            <p><a href="{% url "quizzes:home" %}">< Back to Quizzes</a></p>
            {% if question_response.choice.is_correct %}
                <div class="alert alert-success" role="alert">
                  Correct! Good job!
                </div>

            {% else %}
                <div class="alert alert-danger" role="alert">
                  It looks like your answer is wrong!
                </div>

            {% endif %}

            <h1>{{ quiz }}<span class="badge badge-secondary float-right">{{ question_response.question.category }}</span></h1>

            <br><br>

            <h3 class="text-center">{{ question_response.question.question_text }}</h3>

            <form>
                {% for choice in question_response.question.choices.all %}
                <br><br>
                <div class="form-check">
                  <input disabled class="form-check-input" type="radio" name="answer-chosen" id="{{ choice.id }}" value="{{ choice.id }}"
                         {% if choice.id == question_response.choice.id %}checked {% endif %}
                  >
                  <label class="form-check-label" for="{{ choice.id }}">
                    {{ choice.choice_text }}
                  </label>
                </div>
                {% endfor %}
                <br><br><br>
                {% if next_question_id %}
                    <a href="{% url "quizzes:quiz-question-view" quiz.id next_question_id %}" class="btn btn-secondary btn-lg active float-right" role="button" aria-pressed="true">Next Question -></a>
                {% else %}
                    <a href="{% url "quizzes:quiz-results-view" quiz.id %}" class="btn btn-secondary btn-lg active float-right" role="button" aria-pressed="true">View Final Results</a>
                {% endif %}
                <br><br><br>
            </form>

        </div>
    </section>

</main>


{% endblock %}

quizzle2/templates/quizzes/quiz_results.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}Quizzle 2{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
<main>
    <section class="jumbotron">
        <div class="container">
            {% include "_messages.html" %}
            <h1>{{ quiz }} Results</h1>
        </div>
    </section>
    <section id="content-section">
        <div id="content-body">

            <p><a href="{% url "quizzes:home" %}">< Quizzes</a></p>

            <br>
            <h1>Total Score: {{ total_score|floatformat:"0" }}%</h1>

            <br><br>
            <h3>Questions</h3>

            <table class="table">
              <thead>
                <tr>
                  <th style="width: 5%" scope="col">#</th>
                  <th style="width: 35%" scope="col">Question</th>
                  <th style="width: 10%" scope="col">Feedback</th>
                </tr>
              </thead>
              <tbody>
                {% for qr in quiz.responses.all %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                    <!--<td><a href="{% url "quizzes:quiz-view" quiz.id %}">{{ q }}</a></td>-->
                    <td><a href="{% url "quizzes:quiz-question-view" quiz.id qr.question.id %}">{{ qr.question.question_text }}</a></td>
                  <td class="text-center" style="font-size: 200%;">{% if qr.choice.is_correct %}<i style="color: green;" class="fas fa-check"></i>{% else %}<i style="color: red;" class="fas fa-times"></i>{% endif %}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
                {{ q }}

        </div>
    </section>

</main>


{% endblock %}